### PR TITLE
Added a new theme - purple, minor theme manager changes

### PR DESCRIPTION
**Pull request by Bamboooz**
What did i change?
1) Modified theme_manager.py so that will accept simmilar themes like 'Blue', 'BluE', 'blue' as a blue theme, before it only accepted 'blue' as a vaild theme,
2) Added a purple theme,
3) Modified all examples so that you can see purple theme in the comments after the set color theme,
4) Did the same in the Readme.md file which got an example code piece with the same comment.

### CODE REVIEW

**Comment by caiocv18** [comment]
I really liked this change to have a purple theme, I was thinking of doing an orange theme and this gave me a good idea of the places that need to be changed. Hopefully Tom will accept this PR, from what I saw there are still some open since the middle of last year

**Comment by Bamboooz** [comment]
I am planning to make more themes as well! It is my first contribution to any other project than mine and as I am not that good at programming, I just decided to help a proejct I really enjoy using by adding simple themes.

**Comment by caiocv18** [comment]
Excellent initiative! This really is a great project to contribute, Tom has done a great job making Tkinter more beautiful and fluid to use for screen development. I wish you much success in your planning!

**Comment by mycodesucksx2** [comment]
How would you set it up to switch themes on the fly in your own ctk gui?

**Comment by Bamboooz** [comment]
image
If you mean a switch like this, then in my ctk application I implemented theme switching using a option menu.

### some placeholders

```python
self.color_theme_options = ['Blue', 'Green', Dark-blue']
```

### the switch

```python
self.color_theme_selector = customtkinter.CTkOptionMenu(self.color_theme_frame, values=self.color_theme_options, command=self.change_color_theme_event)
        self.color_theme_selector.grid(row=0, column=3, padx=15)
```

### the change color theme event

```python
    def change_color_theme_event(self, new_color_theme):
        self.color_theme_options = self.sort_list_by_keyword(self.color_theme_options, new_color_theme)  # it is only made because my application has pages and if you were to go to another page and return it might be like you got green theme but it shows blue as the top element

        self.color_theme = new_color_theme

        self.save_major_settings()
```

### sorting function

```python
    def sort_list_by_keyword(lst, keyword):
        index = lst.index(keyword)
        return [lst[index]] + lst[:index] + lst[index + 1:]
```

### save major settings function - a function that will restart the CTk so the color theme changes apply

```python
def save_major_settings(self):
    self.destroy()
    app = App()
    app.mainloop()
```

If I forgot to include something, please tell me.

**Pull request closed without merging**
