### PR TITLE
Scrollable Frame for CustomTkinter

### PR DESCRIPTION
**Pull request by DesignofIntelligence**
Scrollable frames allow you to put any kind of components inside of a window that allows you to scroll (including frames themselves). 
It is used a lot and isn't implemented in any library so I decided to do it.

### CODE REVIEW

**Comment by S1lentAFK** [comment]
Hey, great work. I really needed this in my project. You really came in clutch here. But could you please give an example on how to use it?
Thank you bro!

**Comment by DesignofIntelligence** [comment]
I provided this example inside of a comment in the code

`parent_scrollable = customtkinter.ScrollableFrame(parent)`
    `item = customtkinter.CTkFrame(master=parent_scrollable.scrollable_frame)`
    
the item frame you created will appear on the scrollable frame.

**Comment by S1lentAFK** [comment]
Ok, but I have a problem with even importing the frame. Every time I try to do it, it says that customtkinter has no attribute ScrollableFrame.

**Comment by DesignofIntelligence** [comment]
I forgot to add it to the init.py
I committed, try it again.
`
parent_scrollable = customtkinter.CTkScrollableFrame(parent)
item = customtkinter.CTkFrame(master=parent_scrollable.scrollable_frame)
`

**Comment by S1lentAFK** [comment]
image

Now this is the problem?
Any idea on what to do?

**Comment by DesignofIntelligence** [comment]
There was a bug in the imports, fixed it.

**Comment by S1lentAFK** [comment]
Hi, just to let you know everything works fine, but the scrolling upwards bug just keeps happening. Do you have any idea how to fix it?

**Comment by DesignofIntelligence** [comment]
I am glad it works.
I could not find a way to prevent the user from scrolling upwards. This bug started happening I believe in the new customtkinter version (I wrote the code for 4.6.3)

**Comment by S1lentAFK** [comment]
I tried setting my customtkinter to 4.6.3, but then there was a problem since in that version CTkImage was not introduced yet and in my code I have a couple of them. So that falls out. Lets just hope that nobody scrolls upwards.

**Comment by DesignofIntelligence** [comment]
@TomSchimansky are there any improvements I could make?

**Comment by UserJoo9** [comment]
how can I use scrollable frame in my project.
I was tried to use canvas and too much layer of widgets to make frame scrollable,
but not works fine.

**Comment by cansik** [comment]
Would it be possible to provide a full example? I am not able to get it running in 5.0.5 to display something.

**Comment by bfedie518** [comment]
CustomTkinter now includes a scrollable frame, so this pull request can probably be closed.

**Pull request closed without merging**
