### PR TITLE
Delete examples directory

### PR DESCRIPTION
**Pull request by adithyahk46**

### CODE REVIEW

**Comment by adithyahk46** [comment]
ghghh

**Comment by Dylan-Marsili** [comment]
why

**Comment by AmeyaVS** [comment]
This is a useless PR, better to close this PR.

**Review by its-joseph-230606 — CHANGES_REQUESTED** [review]
useless.

**Comment by adithyahk46** [comment]
Don't worry i will figure it out,

**Comment by AmeyaVS** [comment]
@adithyahk46 , There is no point in opening PR, if there is no value being added.
What are you trying to figure out?

**Pull request closed without merging**
