### PR TITLE
Dialogs

### PR DESCRIPTION
**Pull request by dmtzs**
Added two more dialogs for path and file selections

### CODE REVIEW

**Comment by dmtzs** [comment]
@TomSchimansky I added two more dialogs to be used with custom tkinter and also I included a few examples of each new component as part of this PR, please review and let me know your thoughts, merging to develop branch in order to test :)

**Comment by dmtzs** [comment]
@TomSchimansky  the project is dead? so I can fork it and maintain it separately

**Comment by dmtzs** [comment]
Deleted as the project is dead

**Comment by dipeshSam** [comment]
@dmtzs There are still some chances. Did you read https://github.com/TomSchimansky/CustomTkinter/discussions/2343 conversation?

**Pull request closed without merging**
