### PR TITLE
Update ctk_textbox.py

### PR DESCRIPTION
**Pull request by Qwabena-Proxy**
Fixed 
* AttributeError ‘CTKTextbox’ has no attribute ‘delete’
*AttributeError ‘CTKTextbox’ has no attribute ‘get’

### CODE REVIEW

**Comment by Barry-sze** [comment]
Can not use get value from CTKTextbox

**Comment by Qwabena-Proxy** [comment]
> Can not use get value from CTKTextbox

You can check the changes i made and then update your CTKTextbox and it will work

**Comment by sim2511** [comment]
Thanks a lot Qwabena !!!!!!!!!!!!!!!!!

**Comment by Qwabena-Proxy** [comment]
> Thanks a lot Qwabena !!!!!!!!!!!!!!!!!

You welcome 🙏🏽 🙂

**Comment by Evolution0** [comment]
Would be nice to see this merged, while its not difficult to do:
```python
text_box = CTkTextbox()
text_box.textbox.get()
text_box.textbox.delete('1.0', END)
```

Its unnecessarily verbose (more so depending on imports) and unintuitive as most individuals first reaction will be to treat the CTk widgets just like native Tk ones, parity here would be nice.

**Comment by TomSchimansky** [comment]
Already implemented in develop branch.

**Pull request closed without merging**
