### PR TITLE
Upgrade project config

### PR DESCRIPTION
**Pull request by demberto**
I have named the commits clearly. Apart from that, I suggest you to:
- Begin using semver based versioning `major.minor.patch` and log all the changes.
- Use some sort of test framework which also allows you to setup coverage reporting etc.
- Adopt formatters and linters like black and flake8 to ensure code quality.
- CI/CD with Github actions for automatic releases, PyPi uploads, testing etc.

If you are interested in any of the above, please let me know, I can help

### CODE REVIEW

**Comment by TomSchimansky** [comment]
Thank you very much for providing these commits and suggestions. But before I merge, how does the setup.cfg build process look like compared to setup.py and why should I switch to a setup.cfg file? And how do I use tbump, with the `tbump <version>` command inside the project folder?

**Comment by demberto** [comment]
> How does the `setup.cfg` build process look like compared to `setup.py`

Same.

> Why should I switch to a `setup.cfg` file?

- Secure (you can't run arbitrary code, _either accidentally or maliciously_) in `setup.cfg`.
- A better format for holding metadata, you didn't need to perform any special build steps _like libraries like Pillow / PIL for 
  example, have to_ in your `setup.py` anyways. It just held metadata like name, author etc.
- Support for formatting with the [setup-cfg-fmt](https://github.com/asottile/setup-cfg-fmt) pre-commit hook.

> How do I use `tbump`? With the `tbump <version>` command inside the project folder?

Yes.

**Comment by TomSchimansky** [comment]
Thanks, I will adopt semantic versioning and changelogs from now on. For the other things I will do some research, especially for the testing framework. Can you suggest some frameworks especially for UI testing? I already thought to write some python unit test, but then I just created a lot of example test programs, because the most things that can go wrong can only be seen visually.

**Comment by demberto** [comment]
> Can you suggest some frameworks especially for UI testing?

There are none, atleast for tkinter, I use `pytest` myself. Your existing tests in the `test` folder can be easily ported to use `pytest`. I agree visual feedback is the only way to find a bug in the layout. But this can probably be automated via the `winfo_*` methods once you know what works. Also, tkinter widgets can be named if you didn't know, which gives it a name inside the Tk interpreter. This can be helpful for testing with the `winfo_*` methods I mentioned.

You must check out the testing employed by [Porcupine](https://github.com/Akuli/porcupine), a code editor written entirely with tkinter and Python.

**Pull request merged**
