### PR TITLE
change tabview select method to minimize flickering even more #1508

### PR DESCRIPTION
**Pull request by eirnym**

### CODE REVIEW

**Comment by gdcmarinho** [comment]
Any updates on this, @TomSchimansky?

**Comment by VillainousSsnake** [comment]
bump @TomSchimansky

**Comment by VillainousSsnake** [comment]
@eirnym An error occours:

`AttributeError: 'CTkTabview' object has no attribute '_set_grid_tab_by_name'`

**Comment by eirnym** [comment]
I believe some internals has been changed and it is not applicable. 

I'm not interested in supporting this PR as @TomSchimansky is not interesting to merge it for at least 8 months. Since I released that I migrated all my project to other frameworks.

**Pull request closed without merging**
