### PR TITLE
Default Ctk logo on windows

### PR DESCRIPTION
**Pull request by rc4000**
now the ctk logo is shown by default when creating a window

img2
img1

### CODE REVIEW

**Comment by TomSchimansky** [comment]
Thats a nice addition, I already thought about doing this. But I tried it on macOS and the iconbitmap method had no effect on the icon, so it does not work on macOS. Maybe I will find an other method or it will just work on Windows, I will think about this.

**Comment by sumeshir26** [comment]
On macOS you can use the `.iconphoto` method to set a PNG

**Comment by rc4000** [comment]
> Thats a nice addition, I already thought about doing this. But I tried it on macOS and the iconbitmap method had no effect on the icon, so it does not work on macOS. Maybe I will find an other method or it will just work on Windows, I will think about this.

**Comment by TomSchimansky** [comment]
I added the the titlebar icon for Windows now with a correctly cropped image, try-except block and path handling with os.path.join, so I will close this. But thanks for the request.

**Pull request closed without merging**
