### PR TITLE
added bind method

### PR DESCRIPTION
**Pull request by felipetesc**
You will need to verify this. The change was made at the end of the file. You need to add the signature of the method as tkinter's bind method implements

### CODE REVIEW

**Comment by ghanteyyy** [comment]
It overrides the default bindings of the respective widgets.

**Comment by TomSchimansky** [comment]
I think I will try make the whole widget inherit from tkinter.Canvas directly and not from tkinter.Frame, and the the .bind functions should work fine. Same for the CTkButton or other widgets.

**Comment by ghanteyyy** [comment]
Thanks for the update. Also please update the new version in **PYPI** so that we can update it through
`pip install customtkinter -U`.

**Comment by TomSchimansky** [comment]
I will do, but I have to properly test the HighDPI scaling I implemented.

**Comment by felipetesc** [comment]
The result of this modification is not satisfactory. The slider movement is truncated losing its fluidity when clicking and dragging the component button.

I believe that the self.canvas.bind("<B1-Motion>", self.clicked) method needs to receive a callback with a different implementation other than the click method.

**Comment by TomSchimansky** [comment]
I didn't merged this pull request

**Pull request closed without merging**
