### PR TITLE
OK / Cancel Bug

### PR DESCRIPTION
**Pull request by sternflyer**
Fixed the bug to distinguish whether Ok or Cancel was clicked

### CODE REVIEW

**Review by ArielMAJ — APPROVED** [review]
I tested this locally and the cancel behavior seems to work fine now (it's returning None when cancelling).

**Comment by ArielMAJ** [comment]
PS.: this probably solves #836

**Comment by TomSchimansky** [comment]
Will have a look at this!

**Comment by amuhs** [comment]
Any idea when this might be merged? No, rush. Just trying to decide if I want to wait, or write a workaround for this.

**Comment by MichelDiz** [comment]
This will solve my issue. I can check something like `dialog.get_input() == None` when the user cancels it returns None for get_input with this PR.

**Comment by felix642** [comment]
Any update on this PR?

**Pull request closed without merging**
