### PR TITLE
:hammer: Add active state color for button, User Fonts Directory on Linux - #317 , #340

### PR DESCRIPTION
**Pull request by lmwenda**
#351 
#317 
- Implemented Active State Color for Buttons
- Change code from using `is Not` to `!=`

Hope this helps.

### CODE REVIEW

**Comment by splewdge** [comment]
Btw, using `is` / `is not` is acceptable when checking against a keyword (e.g. `x is True`), since keyword values are unchangeable.

**Comment by lmwenda** [comment]
Ah alright

**Comment by lmwenda** [comment]
#340 
Solved with the new recent commit hopefully

**Comment by lmwenda** [comment]
@TomSchimansky  May you please review this pull request?

**Comment by TomSchimansky** [comment]
Thanks for the pull request, but I will add active color maybe later and then for more widgets.

**Pull request closed without merging**
