### PR TITLE
Added a Dictionary example made with CustomTkinter

### PR DESCRIPTION
**Pull request by TheFallen-Cat**
I added a dictionary made with CustomTkinter to the `examples` folder

### CODE REVIEW

**Comment by TheFallen-Cat** [comment]
@TomSchimansky check it out, I'm open for changes!

**Comment by TheFallen-Cat** [comment]
@TomSchimansky Can you visit the Repo and see if it should get added to the examples?

**Comment by TomSchimansky** [comment]
Looks good, that's a nice project, but I won't add it this repository. I want to have just a few example programs in the examples folder, that have no logic code, so they are easier to read. Maybe I will create a showcase section in the wiki at some point, then I will add your project there!

**Comment by TheFallen-Cat** [comment]
Yeah sure! Thanks, i'll be waiting for that showcase section. Cheers!

**Pull request closed without merging**
